### ISSUE TITLE
Unable to create a compute profile with LXc

### ISSUE THREAD

**Issue by Denjag** [tristanrobert/foreman_fog_proxmox#42]
**Describe the bug**
When i try to create a new compute profile for a compute resource with type LXC container, i have this following error:
"""
Oups, désolé quelque chose s'est mal passé undefined method `first' for nil:NilClass
"""

Logs associate with this error:
2018-11-02T18:41:07 [I|app|] Started POST "/compute_profiles/4-LXC/compute_attributes" for 172.17.1.17 at 2018-11-02 18:41:07 +0100
2018-11-02T18:41:07 [I|app|27aec] Processing by ComputeAttributesController#create as HTML
2018-11-02T18:41:07 [I|app|27aec]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"...", "compute_attribute"=>{"vm_attrs"=>{"type"=>"lxc", "ostemplate_storage"=>"", "ostemplate_file"=>"", "password"=>"[FILTERED]", "config_attributes"=>{"description"=>"", "onboot"=>"0", "arch"=>"amd64", "cores"=>"1", "cpulimit"=>"", "cpuunits"=>"", "memory"=>"536870912", "swap"=>"", "nameserver"=>"", "searchdomain"=>"", "ostype"=>"debian"}, "interfaces_attributes"=>{"0"=>{"name"=>"", "tag"=>"", "rate"=>"", "bridge"=>"vmbr0", "id"=>"net0"}}, "volumes_attributes"=>{"0"=>{"storage"=>"kvm-disks", "size"=>"8589934592", "id"=>"rootfs"}}}, "compute_profile_id"=>"4", "compute_resource_id"=>"1"}, "commit"=>"Valider", "compute_profile_id"=>"4-LXC"}
2018-11-02T18:41:07 [I|app|27aec] Current user set to ... (admin)
2018-11-02T18:41:07 [E|app|27aec] Failed to save: Profil de calcul n'est pas disponible, Ressource de calcul n'est pas disponible
2018-11-02T18:41:07 [I|app|27aec]   Rendering compute_attributes/new.html.erb within layouts/application
2018-11-02T18:41:07 [I|app|27aec]   Rendered compute_attributes/_form.html.erb (479.6ms)
2018-11-02T18:41:07 [I|app|27aec]   Rendered compute_attributes/new.html.erb within layouts/application (516.6ms)
2018-11-02T18:41:07 [W|app|27aec] Action failed
 | ActionView::Template::Error: undefined method `first' for nil:NilClass
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-proxmox-0.5.2/lib/fog/proxmox/helpers/nic_helper.rb:45:in `extract_name'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-proxmox-0.5.2/lib/fog/compute/proxmox/models/container_config.rb:86:in `block in compute_nets'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-proxmox-0.5.2/lib/fog/compute/proxmox/models/container_config.rb:83:in `each'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-proxmox-0.5.2/lib/fog/compute/proxmox/models/container_config.rb:83:in `compute_nets'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-proxmox-0.5.2/lib/fog/compute/proxmox/models/container_config.rb:61:in `initialize'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-proxmox-0.5.2/lib/fog/compute/proxmox/models/container.rb:58:in `new'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-proxmox-0.5.2/lib/fog/compute/proxmox/models/container.rb:58:in `set_config'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-proxmox-0.5.2/lib/fog/compute/proxmox/models/server.rb:59:in `initialize'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-core-1.45.0/lib/fog/core/collection.rb:88:in `new'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-core-1.45.0/lib/fog/core/collection.rb:88:in `new'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-proxmox-0.5.2/lib/fog/compute/proxmox/models/servers.rb:39:in `new'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/fog-proxmox-0.5.2/lib/fog/compute/proxmox/models/containers.rb:38:in `new'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/foreman_fog_proxmox-0.5.3/app/models/foreman_fog_proxmox/proxmox.rb:206:in `new_container_vm'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/foreman_fog_proxmox-0.5.3/app/models/foreman_fog_proxmox/proxmox.rb:197:in `new_vm'
 | /usr/share/foreman/app/views/compute_attributes/_form.html.erb:7:in `block in _774b1727827c7173d33736321f26f786'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/helpers/capture_helper.rb:39:in `capture'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/helpers/form_helper.rb:450:in `form_for'
 | /usr/share/foreman/app/helpers/form_helper.rb:296:in `form_for'
 | /usr/share/foreman/app/views/compute_attributes/_form.html.erb:1:in `_774b1727827c7173d33736321f26f786'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:157:in `block in render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:352:in `instrument_render_template'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:155:in `render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/deface-1.3.2/lib/deface/action_view_extensions.rb:41:in `render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:342:in `block in render_partial'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:331:in `render_partial'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/partial_renderer.rb:310:in `render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:47:in `render_partial'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/helpers/rendering_helper.rb:35:in `render'
 | /usr/share/foreman/app/views/compute_attributes/new.html.erb:23:in `_9be5211cfd188a17e3ad4d62c975069b'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:157:in `block in render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:352:in `instrument_render_template'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/template.rb:155:in `render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/deface-1.3.2/lib/deface/action_view_extensions.rb:41:in `render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:52:in `block (2 levels) in render_template'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:51:in `block in render_template'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:50:in `render_template'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/template_renderer.rb:14:in `render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:42:in `render_template'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/renderer/renderer.rb:23:in `render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/rendering.rb:103:in `_render_template'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/streaming.rb:217:in `_render_template'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/rendering.rb:83:in `render_to_body'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/renderers.rb:141:in `render_to_body'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/rendering.rb:24:in `render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:36:in `render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
 | /usr/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/core_ext/benchmark.rb:12:in `ms'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/railties/controller_runtime.rb:29:in `cleanup_view_runtime'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:43:in `render'
 | /usr/share/foreman/app/controllers/application_controller.rb:307:in `process_error'
 | /usr/share/foreman/app/controllers/compute_attributes_controller.rb:14:in `create'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:186:in `process_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/rendering.rb:30:in `process_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
 | /usr/share/foreman/app/controllers/concerns/application_shared.rb:15:in `set_timezone'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 | /usr/share/foreman/app/models/concerns/foreman/thread_session.rb:32:in `clear_thread'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 | /usr/share/foreman/app/controllers/concerns/foreman/controller/topbar_sweeper.rb:12:in `set_topbar_sweeper_controller'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/audited-4.8.0/lib/audited/sweeper.rb:14:in `around'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/audited-4.8.0/lib/audited/sweeper.rb:14:in `around'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:135:in `run_callbacks'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/rescue.rb:20:in `process_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `block in instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/notifications.rb:166:in `instrument'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activerecord-5.1.6/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/abstract_controller/base.rb:124:in `process'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionview-5.1.6/lib/action_view/rendering.rb:30:in `process'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal.rb:189:in `dispatch'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_controller/metal.rb:253:in `dispatch'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:31:in `serve'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:50:in `block in serve'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33:in `each'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/journey/router.rb:33:in `serve'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/routing/route_set.rb:844:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/apipie-rails-0.5.10/lib/apipie/static_dispatcher.rb:65:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/apipie-rails-0.5.10/lib/apipie/extractor/recorder.rb:136:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/static.rb:125:in `call'
 | /usr/share/foreman/lib/middleware/telemetry.rb:9:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/apipie-rails-0.5.10/lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
 | /usr/share/foreman/lib/middleware/catch_json_parse_errors.rb:8:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/conditional_get.rb:38:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
 | /usr/share/foreman/lib/middleware/logging_context.rb:23:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/cookies.rb:613:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/callbacks.rb:97:in `run_callbacks'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:36:in `call_app'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/railties-5.1.6/lib/rails/rack/logger.rb:26:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/request_id.rb:25:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/activesupport-5.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/executor.rb:12:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/actionpack-5.1.6/lib/action_dispatch/middleware/static.rb:125:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/secure_headers-5.0.5/lib/secure_headers/middleware.rb:13:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/railties-5.1.6/lib/rails/engine.rb:522:in `call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/railties-5.1.6/lib/rails/railtie.rb:185:in `public_send'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/railties-5.1.6/lib/rails/railtie.rb:185:in `method_missing'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/urlmap.rb:68:in `block in call'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `each'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/rack-2.0.5/lib/rack/urlmap.rb:53:in `call'
 | /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
 | /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
 | /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
 | /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
 | /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
 | /usr/share/foreman/vendor/ruby/2.3.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
2018-11-02T18:41:07 [I|app|27aec]   Rendering common/500.html.erb within layouts/application
2018-11-02T18:41:07 [I|app|27aec]   Rendered common/500.html.erb within layouts/application (2.6ms)
2018-11-02T18:41:07 [I|app|27aec]   Rendered layouts/_application_content.html.erb (1.8ms)
2018-11-02T18:41:07 [I|app|27aec]   Rendering layouts/base.html.erb
2018-11-02T18:41:07 [I|app|27aec]   Rendered layouts/base.html.erb (2.5ms)
2018-11-02T18:41:07 [I|app|27aec] Completed 500 Internal Server Error in 594ms (Views: 9.7ms | ActiveRecord: 12.4ms)
2018-11-02T18:41:07 [I|app|de51b]   Rendering text template
2018-11-02T18:41:07 [I|app|de51b]   Rendered text template (0.0ms)

**To Reproduce**
1. Create a compute resource
2. Create a new compute profile on this resource, with type LXC (whatever parameters)
3. Validate

**Expected behavior**
Just no error, create the compute profile as expected

**Desktop (please complete the following information):**
 - OS: Server running on Debian 9.5

Thanks for your help

**Comment by tristanrobert** [comment]
Hello, you must enter a valid name like eth0 to your nic. It's required by Proxmox.
